chore: Copy path_util over from separate project
omec-project/util pull request #17
Opened 2024-02-06 15:11 UTC by ghislainbourgeois

Copies the code from the separate `path_util` module to this collection of dependencies. This currently does not impact any NFs as they are still pointing to the old project.

2024-02-06 22:09 UTC, gab-arrobo requested changes

2024-02-06 22:09 UTC, gab-arrobo commented on path_util/logger/logger.go
Please add copyright/license header

2024-02-06 22:09 UTC, gab-arrobo commented on path_util/path.go
Please add copyright/license header

2024-02-06 22:09 UTC, gab-arrobo commented on path_util/path_test.go
Please add copyright/license header

2024-02-07 02:33 UTC, ghislainbourgeois commented on path_util/logger/logger.go
Done

2024-02-07 02:33 UTC, ghislainbourgeois commented on path_util/path.go
Done

2024-02-07 02:33 UTC, ghislainbourgeois commented on path_util/path_test.go
Done

2024-02-07 02:43 UTC, merged